/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as IgnaTokenomicsRouteImport } from './routes/igna-tokenomics'
import { Route as HowToBuyIgnaRouteImport } from './routes/how-to-buy-igna'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LangLandingRouteImport } from './routes/$lang/landing'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const IgnaTokenomicsRoute = IgnaTokenomicsRouteImport.update({
  id: '/igna-tokenomics',
  path: '/igna-tokenomics',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToBuyIgnaRoute = HowToBuyIgnaRouteImport.update({
  id: '/how-to-buy-igna',
  path: '/how-to-buy-igna',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLandingRoute = LangLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/docs': typeof DocsRoute
  '/how-to-buy-igna': typeof HowToBuyIgnaRoute
  '/igna-tokenomics': typeof IgnaTokenomicsRoute
  '/swap': typeof SwapRoute
  '/$lang/landing': typeof LangLandingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/docs': typeof DocsRoute
  '/how-to-buy-igna': typeof HowToBuyIgnaRoute
  '/igna-tokenomics': typeof IgnaTokenomicsRoute
  '/swap': typeof SwapRoute
  '/$lang/landing': typeof LangLandingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/docs': typeof DocsRoute
  '/how-to-buy-igna': typeof HowToBuyIgnaRoute
  '/igna-tokenomics': typeof IgnaTokenomicsRoute
  '/swap': typeof SwapRoute
  '/$lang/landing': typeof LangLandingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/docs'
    | '/how-to-buy-igna'
    | '/igna-tokenomics'
    | '/swap'
    | '/$lang/landing'
    | '/blog/$slug'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/docs'
    | '/how-to-buy-igna'
    | '/igna-tokenomics'
    | '/swap'
    | '/$lang/landing'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/docs'
    | '/how-to-buy-igna'
    | '/igna-tokenomics'
    | '/swap'
    | '/$lang/landing'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  DocsRoute: typeof DocsRoute
  HowToBuyIgnaRoute: typeof HowToBuyIgnaRoute
  IgnaTokenomicsRoute: typeof IgnaTokenomicsRoute
  SwapRoute: typeof SwapRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igna-tokenomics': {
      id: '/igna-tokenomics'
      path: '/igna-tokenomics'
      fullPath: '/igna-tokenomics'
      preLoaderRoute: typeof IgnaTokenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-buy-igna': {
      id: '/how-to-buy-igna'
      path: '/how-to-buy-igna'
      fullPath: '/how-to-buy-igna'
      preLoaderRoute: typeof HowToBuyIgnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/landing': {
      id: '/$lang/landing'
      path: '/landing'
      fullPath: '/$lang/landing'
      preLoaderRoute: typeof LangLandingRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangLandingRoute: typeof LangLandingRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangLandingRoute: LangLandingRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  DocsRoute: DocsRoute,
  HowToBuyIgnaRoute: HowToBuyIgnaRoute,
  IgnaTokenomicsRoute: IgnaTokenomicsRoute,
  SwapRoute: SwapRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
